const NS_DAYCARE = "daycare";

const NEW_DAYCARE_REQUEST = `${NS_DAYCARE}/newDayCareRequest`;
const NEW_DAYCARE_SUCCESS = `${NS_DAYCARE}/newDayCareSuccess`;
const NEW_DAYCARE_FAIL = `${NS_DAYCARE}/newDayCareFail`;

const ACTIVITIES_GETALL_REQUEST = `${NS_DAYCARE}/activitiesGetAllRequest`;
const ACTIVITIES_GETALL_SUCCESS = `${NS_DAYCARE}/activitiesGetAllSuccess`;
const ACTIVITIES_GETALL_FAIL = `${NS_DAYCARE}/activitiesGetAllFail`;

export {
    NEW_DAYCARE_REQUEST, NEW_DAYCARE_SUCCESS, NEW_DAYCARE_FAIL,
    ACTIVITIES_GETALL_REQUEST, ACTIVITIES_GETALL_SUCCESS, ACTIVITIES_GETALL_FAIL
};